//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.12 at 05:38:16 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.com.ibm/courses", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ibm.com.courses;
